name: Test Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test-pull-request:
    name: test pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run component unit tests
        id: bun-test-client
        run: bun test
      # Bun's test config seems like it might not be
      # flexible enough to support multiple test configs
      # or roots. I will need to think of a better long
      # term solution for this
      - name: Run lib unit tests
        id: bun-test-lib
        run: bun test ./lib/actions/__tests__/actions.ts
